---
output: html_document
---

```{r, include=FALSE}
library(magrittr)
library(knitr)
opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE, cache = FALSE, #fig.width = 9, fig.height = 9, 
  results = 'hide', out.width = '100%', out.height = '100vh')
```

```{r}
# Carrega os dados do repositório-irmão febr-data
load('../../febr-data/data/r/obs.rda')
load("../../febr-data/data/r/febr-chaves.rda")
```

```{r}
obs <- lapply(1:nrow(sheets_keys), function (i) 
  data.frame(
    obs[[i]][c("observacao_id", "coord_x", "coord_y")], id = sheets_keys$ctb[i], stringsAsFactors = FALSE))
febr <- na.exclude(do.call(rbind, obs))
febr$observacao_id <- glue::glue("{febr$observacao_id}@{febr$id}")
```

```{r}
febr$id <- 
  glue::glue('<a href="http://www.ufsm.br/febr/catalog/{febr$id}.html" target="_blank">Mais informações?</a>')
```

```{r, eval=FALSE}
# febr <- sf::st_as_sf(febr, coords = c("coord_x", "coord_y"), crs = 4674)
```

```{r, results='asis', eval=FALSE}
# logo <- 'logo.svg'
# mapview::mapview(
#   febr, label = febr$observacao_id, popup = glue::glue('{febr$id}', sep = ""),
#   map.types = c("Esri.WorldTopoMap", "CartoDB.Positron", "Esri.WorldImagery"),
#   col.regions = "firebrick1", lwd = 1, col = "ivory") %>% 
#   mapview::addLogo(img = logo, url = "http://www.ufsm.br/febr/")
```

```{r, results='asis', eval=TRUE}
logo <- 'logo.svg'
leaflet::leaflet() %>%
  leaflet::addProviderTiles("Esri.WorldTopoMap", group = "Esri.WorldTopoMap") %>% 
  leaflet::addProviderTiles("CartoDB.Positron", group = "CartoDB.Positron") %>% 
  leaflet::addProviderTiles("Esri.WorldImagery", group = "Esri.WorldImagery") %>% 
  leaflet::addAwesomeMarkers(
    lng = febr$coord_x,
    lat = febr$coord_y,
    icon = leaflet::awesomeIcons(icon = "info-sign", markerColor = "#b22222", iconColor = "#fffff0"),
    popup = febr$id,
    clusterOptions = leaflet::markerClusterOptions(),
    label = febr$observacao_id) %>%
  leaflet::addLayersControl(
    baseGroups = c("Esri.WorldTopoMap", "CartoDB.Positron", "Esri.WorldImagery"),
    options = leaflet::layersControlOptions(collapsed = FALSE)) %>% 
  mapview::addLogo(img = logo, url = "http://www.ufsm.br/febr/") %>% 
  mapview::addHomeButton(
    ext = raster::extent(sf::st_as_sf(febr, coords = c("coord_x", "coord_y"), crs = 4674)), 
    layer.name = "Ver tudo", position = "bottomleft") %>%
  leaflet::addMiniMap()
```
